// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfkp4kIxybSI3P0Ry0dTjBwf0IGDBP7Ms',
    appId: '1:52781004924:web:34edeb85a436452a5c31f9',
    messagingSenderId: '52781004924',
    projectId: 'email-transactions-reader',
    authDomain: 'email-transactions-reader.firebaseapp.com',
    storageBucket: 'email-transactions-reader.appspot.com',
    measurementId: 'G-6Z7XWXCB3Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIVVIeDdfgZDLScwY0wCRL191ziuQgQZs',
    appId: '1:52781004924:android:5c59a45ca59a52cb5c31f9',
    messagingSenderId: '52781004924',
    projectId: 'email-transactions-reader',
    storageBucket: 'email-transactions-reader.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA84L9cFAAcfAu8m6vFDAjirzmvSVn8EQk',
    appId: '1:52781004924:ios:b8c93f64f7479f205c31f9',
    messagingSenderId: '52781004924',
    projectId: 'email-transactions-reader',
    storageBucket: 'email-transactions-reader.appspot.com',
    iosBundleId: 'com.example.expenseManagerClient2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA84L9cFAAcfAu8m6vFDAjirzmvSVn8EQk',
    appId: '1:52781004924:ios:782e6f9812098cc85c31f9',
    messagingSenderId: '52781004924',
    projectId: 'email-transactions-reader',
    storageBucket: 'email-transactions-reader.appspot.com',
    iosBundleId: 'com.example.expenseManagerClient2.RunnerTests',
  );
}
